In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data_train=pd.read_csv('/content/train_dataset (1).csv')
data_test=pd.read_csv('/content/test_dataset (1).csv')

In [ ]:
data_train.head()

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0  7135    1654     CL  D-penicillamine  19581   F       N            N   
1  7326      41      C  D-penicillamine  22880   F     NaN            N   
2  7254     297      D              NaN  27957   F       N            N   
3  3135    1872      C  D-penicillamine  21111   F     NaN            Y   
4  2483     939     CL  D-penicillamine  18061   F     NaN          NaN   

  Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0       Y     N        0.3        279.0     2.96    84.0    1500.8   99.43   
1     NaN     N        0.3          NaN     2.96     NaN    1835.4   26.35   
2     NaN     N        0.3        328.0     2.64     4.0       NaN     NaN   
3       Y     N        0.3        302.0     2.02    49.0       NaN   26.35   
4     NaN     N        0.5        344.0     3.11    91.0       NaN  104.56   

   Tryglicerides  Platelets  Prothrombin  Stage  
0          109.0      293.0         10.2      4  
1          131.0      308.0         10.8      1  
2          116.0      194.0         10.3      3  
3            NaN        NaN         10.5      4  
4            NaN      306.0         11.4      2

In [ ]:
data_test.head()

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0  3870      41      C          Placebo  22553   F       N          NaN   
1  3462    1811      C  D-penicillamine  16223   F       N            Y   
2  1632     954      C  D-penicillamine  27100   F       N            N   
3   722    1969      D          Placebo  17039   F       N            Y   
4  1000    2721      D  D-penicillamine  17738   F     NaN          NaN   

  Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0       N     N        1.4        247.0     3.62     NaN       NaN  108.65   
1       N     N        0.3        311.0     2.80    92.0    1748.1     NaN   
2       N     N        0.4          NaN     3.56     NaN       NaN   43.52   
3       N     N        1.2          NaN     3.16     NaN     617.1  113.76   
4     NaN     N        3.2          NaN     2.36    89.0    1782.4     NaN   

   Tryglicerides  Platelets  Prothrombin  
0            NaN      169.0         11.6  
1          129.0      321.0         11.5  
2            NaN      296.0         10.3  
3            NaN      125.0         10.9  
4          129.0      138.0         10.6

In [ ]:
df=data_train.drop(['ID'], axis=1) #cleaning data by dropping useless data
df1=data_test.drop(['ID'], axis=1) #cleaning data by dropping useless data

In [ ]:
df.head() #train data after dropping the ID column

N_Days Status             Drug    Age Sex Ascites Hepatomegaly Spiders  \
0    1654     CL  D-penicillamine  19581   F       N            N       Y   
1      41      C  D-penicillamine  22880   F     NaN            N     NaN   
2     297      D              NaN  27957   F       N            N     NaN   
3    1872      C  D-penicillamine  21111   F     NaN            Y       Y   
4     939     CL  D-penicillamine  18061   F     NaN          NaN     NaN   

  Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0     N        0.3        279.0     2.96    84.0    1500.8   99.43   
1     N        0.3          NaN     2.96     NaN    1835.4   26.35   
2     N        0.3        328.0     2.64     4.0       NaN     NaN   
3     N        0.3        302.0     2.02    49.0       NaN   26.35   
4     N        0.5        344.0     3.11    91.0       NaN  104.56   

   Tryglicerides  Platelets  Prothrombin  Stage  
0          109.0      293.0         10.2      4  
1          131.0      308.0         10.8      1  
2          116.0      194.0         10.3      3  
3            NaN        NaN         10.5      4  
4            NaN      306.0         11.4      2

In [ ]:
#df1.head()

In [ ]:
#CLEANING THE DATA by changing value of str data to int value
df['Status']=df['Status'].apply({'C':1,'CL':2,'D':3}.get)
df['Drug']=df['Drug'].apply({'D-penicillamine':1,'Placebo':2}.get)
df['Sex']=df['Sex'].apply({'M':1,'F':2}.get)
df['Ascites']=df['Ascites'].apply({'Y':1,'N':2}.get)
df['Hepatomegaly']=df['Hepatomegaly'].apply({'Y':1,'N':2}.get)
df['Spiders']=df['Spiders'].apply({'Y':1,'N':2}.get)
df['Edema']=df['Edema'].apply({'Y':1,'N':2,'S':3}.get)

In [ ]:
df.head() #train data after removing categorical values

N_Days  Status  Drug    Age  Sex  Ascites  Hepatomegaly  Spiders  Edema  \
0    1654       2   1.0  19581    2      2.0           2.0      1.0      2   
1      41       1   1.0  22880    2      NaN           2.0      NaN      2   
2     297       3   NaN  27957    2      2.0           2.0      NaN      2   
3    1872       1   1.0  21111    2      NaN           1.0      1.0      2   
4     939       2   1.0  18061    2      NaN           NaN      NaN      2   

   Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  Tryglicerides  \
0        0.3        279.0     2.96    84.0    1500.8   99.43          109.0   
1        0.3          NaN     2.96     NaN    1835.4   26.35          131.0   
2        0.3        328.0     2.64     4.0       NaN     NaN          116.0   
3        0.3        302.0     2.02    49.0       NaN   26.35            NaN   
4        0.5        344.0     3.11    91.0       NaN  104.56            NaN   

   Platelets  Prothrombin  Stage  
0      293.0         10.2      4  
1      308.0         10.8      1  
2      194.0         10.3      3  
3        NaN         10.5      4  
4      306.0         11.4      2

In [ ]:
d_train=df.replace(np.nan,0) #relacing null values with 0

In [ ]:
d_train.head() #data_set after replacing null values with 0

N_Days  Status  Drug    Age  Sex  Ascites  Hepatomegaly  Spiders  Edema  \
0    1654       2   1.0  19581    2      2.0           2.0      1.0      2   
1      41       1   1.0  22880    2      0.0           2.0      0.0      2   
2     297       3   0.0  27957    2      2.0           2.0      0.0      2   
3    1872       1   1.0  21111    2      0.0           1.0      1.0      2   
4     939       2   1.0  18061    2      0.0           0.0      0.0      2   

   Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  Tryglicerides  \
0        0.3        279.0     2.96    84.0    1500.8   99.43          109.0   
1        0.3          0.0     2.96     0.0    1835.4   26.35          131.0   
2        0.3        328.0     2.64     4.0       0.0    0.00          116.0   
3        0.3        302.0     2.02    49.0       0.0   26.35            0.0   
4        0.5        344.0     3.11    91.0       0.0  104.56            0.0   

   Platelets  Prothrombin  Stage  
0      293.0         10.2      4  
1      308.0         10.8      1  
2      194.0         10.3      3  
3        0.0         10.5      4  
4      306.0         11.4      2

In [ ]:
#df1.head()

In [ ]:
#splitting the data into independent & dependent category
x=d_train.drop(['Stage'],axis=1)
y=d_train['Stage']

In [ ]:
#importing model for training & testing of the model
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2) #size=0.2 means using 20% data for testing & rest 80% for training

In [ ]:
#importing DecissionTree Classifier
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()

In [ ]:
tree.fit(x_train,y_train) #using fit() for training

DecisionTreeClassifier()

In [ ]:
predictions=tree.predict(x_test) #using tree.predict() for prediction

In [ ]:
#accuracy of decision tree model
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
acc=accuracy_score(y_test,predictions)

In [ ]:
print(cm) #checking the performance of model using confusion matrix

[[  3  19  25  42]
 [ 16  72  62 152]
 [ 17  67  53 134]
 [ 68 143 147 340]]


In [ ]:
print(acc) #checking the accuracy of the model using accuracy score

0.34411764705882353


In [ ]:
#importing RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [ ]:
rf.fit(x_train,y_train) #using fit() for training

RandomForestClassifier()

In [ ]:
prediction=rf.predict(x_test) #using rf.predict() for prediction

In [ ]:
#accuracy of decision tree model
from sklearn.metrics import confusion_matrix,accuracy_score
CM=confusion_matrix(y_test,prediction)
ACC=accuracy_score(y_test,prediction)

In [ ]:
print(CM) #checking the performance of model using comfusion matrix

[[  0   0   1  88]
 [  0   7   3 292]
 [  0   5   0 266]
 [  0  11   1 686]]


In [ ]:
print(ACC) #checking the accuracy of the model using accuracy score

0.5095588235294117


Prediction using test_dataset

In [ ]:
df1.head() #test data after dropping the ID column

N_Days Status             Drug    Age Sex Ascites Hepatomegaly Spiders  \
0      41      C          Placebo  22553   F       N          NaN       N   
1    1811      C  D-penicillamine  16223   F       N            Y       N   
2     954      C  D-penicillamine  27100   F       N            N       N   
3    1969      D          Placebo  17039   F       N            Y       N   
4    2721      D  D-penicillamine  17738   F     NaN          NaN     NaN   

  Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0     N        1.4        247.0     3.62     NaN       NaN  108.65   
1     N        0.3        311.0     2.80    92.0    1748.1     NaN   
2     N        0.4          NaN     3.56     NaN       NaN   43.52   
3     N        1.2          NaN     3.16     NaN     617.1  113.76   
4     N        3.2          NaN     2.36    89.0    1782.4     NaN   

   Tryglicerides  Platelets  Prothrombin  
0            NaN      169.0         11.6  
1          129.0      321.0         11.5  
2            NaN      296.0         10.3  
3            NaN      125.0         10.9  
4          129.0      138.0         10.6

In [ ]:
#CLEANING THE DATA by changing value of str data to int value
df1['Status']=df1['Status'].apply({'C':1,'CL':2,'D':3}.get)
df1['Drug']=df1['Drug'].apply({'D-penicillamine':1,'Placebo':2}.get)
df1['Sex']=df1['Sex'].apply({'M':1,'F':2}.get)
df1['Ascites']=df1['Ascites'].apply({'Y':1,'N':2}.get)
df1['Hepatomegaly']=df1['Hepatomegaly'].apply({'Y':1,'N':2}.get)
df1['Spiders']=df1['Spiders'].apply({'Y':1,'N':2}.get)
df1['Edema']=df1['Edema'].apply({'Y':1,'N':2,'S':3}.get)

In [ ]:
df1.head() #train data after removing catogorical values

N_Days  Status  Drug    Age  Sex  Ascites  Hepatomegaly  Spiders  Edema  \
0      41       1   2.0  22553    2      2.0           NaN      2.0      2   
1    1811       1   1.0  16223    2      2.0           1.0      2.0      2   
2     954       1   1.0  27100    2      2.0           2.0      2.0      2   
3    1969       3   2.0  17039    2      2.0           1.0      2.0      2   
4    2721       3   1.0  17738    2      NaN           NaN      NaN      2   

   Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  Tryglicerides  \
0        1.4        247.0     3.62     NaN       NaN  108.65            NaN   
1        0.3        311.0     2.80    92.0    1748.1     NaN          129.0   
2        0.4          NaN     3.56     NaN       NaN   43.52            NaN   
3        1.2          NaN     3.16     NaN     617.1  113.76            NaN   
4        3.2          NaN     2.36    89.0    1782.4     NaN          129.0   

   Platelets  Prothrombin  
0      169.0         11.6  
1      321.0         11.5  
2      296.0         10.3  
3      125.0         10.9  
4      138.0         10.6

In [ ]:
d_test=df1.replace(np.nan,0) #replacing null data's with 0

In [ ]:
d_test.head() #dataset after replacing null values

N_Days  Status  Drug    Age  Sex  Ascites  Hepatomegaly  Spiders  Edema  \
0      41       1   2.0  22553    2      2.0           0.0      2.0      2   
1    1811       1   1.0  16223    2      2.0           1.0      2.0      2   
2     954       1   1.0  27100    2      2.0           2.0      2.0      2   
3    1969       3   2.0  17039    2      2.0           1.0      2.0      2   
4    2721       3   1.0  17738    2      0.0           0.0      0.0      2   

   Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  Tryglicerides  \
0        1.4        247.0     3.62     0.0       0.0  108.65            0.0   
1        0.3        311.0     2.80    92.0    1748.1    0.00          129.0   
2        0.4          0.0     3.56     0.0       0.0   43.52            0.0   
3        1.2          0.0     3.16     0.0     617.1  113.76            0.0   
4        3.2          0.0     2.36    89.0    1782.4    0.00          129.0   

   Platelets  Prothrombin  
0      169.0         11.6  
1      321.0         11.5  
2      296.0         10.3  
3      125.0         10.9  
4      138.0         10.6

In [ ]:
X1_train,X1_test =train_test_split(d_test,test_size = 0.1) #traing the test dataset

In [ ]:
X1_train.shape

(2880, 18)

In [ ]:
X1_test.shape

(320, 18)

Prediction of stage of liver disease using DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
 
tree=DecisionTreeClassifier()
tree.fit(x_train, y_train) #training the test_dataset with train_dataset

DecisionTreeClassifier()

In [ ]:
prediction_test=tree.predict(X1_test) #predicting the stage of disease using test_dataset

In [ ]:
prediction_test #THE PREDICTIONS OF STAGE

array([2, 4, 4, 4, 3, 4, 4, 1, 4, 1, 2, 4, 4, 2, 4, 4, 2, 4, 2, 2, 4, 2,
       4, 4, 4, 2, 2, 4, 3, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 3, 4, 2,
       2, 2, 4, 4, 4, 4, 4, 3, 4, 1, 2, 3, 3, 2, 2, 4, 3, 2, 3, 1, 4, 4,
       3, 2, 4, 1, 2, 4, 4, 4, 3, 1, 4, 1, 4, 4, 3, 3, 4, 4, 4, 4, 3, 2,
       4, 4, 3, 1, 2, 3, 1, 4, 4, 2, 4, 3, 4, 4, 2, 3, 2, 1, 1, 3, 4, 4,
       2, 4, 1, 2, 3, 3, 4, 3, 4, 4, 2, 2, 2, 2, 3, 1, 3, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 4, 2, 4, 4, 4, 3, 2, 4, 2, 4, 4, 2, 4, 4, 2, 2, 3, 4,
       3, 2, 4, 1, 4, 1, 4, 4, 3, 3, 4, 3, 2, 4, 3, 3, 4, 2, 2, 4, 4, 4,
       2, 1, 4, 4, 2, 4, 4, 2, 4, 3, 4, 4, 3, 3, 2, 1, 1, 1, 4, 2, 2, 2,
       3, 3, 3, 1, 2, 1, 3, 2, 2, 4, 4, 4, 4, 1, 4, 4, 1, 4, 1, 3, 2, 1,
       4, 4, 4, 3, 4, 4, 2, 3, 4, 4, 3, 1, 3, 4, 2, 3, 4, 4, 4, 3, 3, 3,
       4, 1, 3, 4, 4, 4, 2, 4, 3, 4, 4, 4, 3, 1, 4, 2, 2, 4, 2, 4, 3, 4,
       4, 4, 4, 3, 4, 2, 3, 3, 4, 2, 4, 4, 4, 4, 4, 4, 4, 1, 3, 3, 2, 4,
       2, 2, 4, 4, 4, 4, 3, 4, 2, 4, 1, 4, 3, 4, 4,

Prediction of stage of liver disease using RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()
rf.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
predict_test=rf.predict(X1_test)

In [ ]:
predict_test

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,