In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
data_train=pd.read_csv('/content/Train_Data.csv')

In [3]:
data_train.head()

city  city_development_index gender      relevent_experience  \
0  city_21                0.624000   Male   No relevent experience   
1  city_21                0.616795   Male   No relevent experience   
2  city_73                0.754000   Male   No relevent experience   
3  city_57                0.866000   Male   No relevent experience   
4  city_21                0.624000   Male  Has relevent experience   

  enrolled_university education_level major_discipline experience  \
0    Full time course        Graduate             STEM          3   
1    Full time course        Graduate             STEM         <1   
2    Full time course        Graduate             STEM         <1   
3       no_enrollment             Phd             STEM          9   
4       no_enrollment         Masters             STEM          5   

  company_size company_type last_new_job  training_hours  target  
0      missing      Pvt Ltd        never       31.372145       1  
1      missing      missing            1       63.988905       1  
2      missing      missing        never       19.000000       1  
3      100-500      Pvt Ltd           >4       53.000000       0  
4        50-99      Pvt Ltd           >4      108.000000       1

In [4]:
df=data_train

In [5]:
x=df.drop(['target'],axis=1)
y=df['target']

In [6]:
x.head()

city  city_development_index gender      relevent_experience  \
0  city_21                0.624000   Male   No relevent experience   
1  city_21                0.616795   Male   No relevent experience   
2  city_73                0.754000   Male   No relevent experience   
3  city_57                0.866000   Male   No relevent experience   
4  city_21                0.624000   Male  Has relevent experience   

  enrolled_university education_level major_discipline experience  \
0    Full time course        Graduate             STEM          3   
1    Full time course        Graduate             STEM         <1   
2    Full time course        Graduate             STEM         <1   
3       no_enrollment             Phd             STEM          9   
4       no_enrollment         Masters             STEM          5   

  company_size company_type last_new_job  training_hours  
0      missing      Pvt Ltd        never       31.372145  
1      missing      missing            1       63.988905  
2      missing      missing        never       19.000000  
3      100-500      Pvt Ltd           >4       53.000000  
4        50-99      Pvt Ltd           >4      108.000000

In [7]:
y.head()

0    1
1    1
2    1
3    0
4    1
Name: target, dtype: int64

Feature engineering for one hot encoding

In [8]:
city=pd.get_dummies(x['city'])
gender=pd.get_dummies(x['gender'])
relevent_experience=pd.get_dummies(x['relevent_experience'])
enrolled_university=pd.get_dummies(x['enrolled_university'])
education_level=pd.get_dummies(x['education_level'])
major_discipline=pd.get_dummies(x['major_discipline'])
experience=pd.get_dummies(x['experience'])
company_size=pd.get_dummies(x['company_size'])
company_type=pd.get_dummies(x['company_type'])
last_new_job=pd.get_dummies(x['last_new_job'])

In [9]:
#concatenate this with dataframe
x=x.drop(['city','gender','relevent_experience','enrolled_university','education_level','major_discipline','experience','company_size','company_type','last_new_job'],axis=1)

In [10]:
x.head()

city_development_index  training_hours
0                0.624000       31.372145
1                0.616795       63.988905
2                0.754000       19.000000
3                0.866000       53.000000
4                0.624000      108.000000

In [11]:
x=pd.concat([x,city,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job],axis=1)

In [12]:
x.head()

city_development_index  training_hours  city_1  city_10  city_100  \
0                0.624000       31.372145       0        0         0   
1                0.616795       63.988905       0        0         0   
2                0.754000       19.000000       0        0         0   
3                0.866000       53.000000       0        0         0   
4                0.624000      108.000000       0        0         0   

   city_101  city_102  city_103  city_104  city_105  ...  Public Sector  \
0         0         0         0         0         0  ...              0   
1         0         0         0         0         0  ...              0   
2         0         0         0         0         0  ...              0   
3         0         0         0         0         0  ...              0   
4         0         0         0         0         0  ...              0   

   Pvt Ltd  missing  1  2  3  4  >4  missing  never  
0        1        0  0  0  0  0   0        0      1  
1        0        1  1  0  0  0   0        0      0  
2        0        1  0  0  0  0   0        0      1  
3        1        0  0  0  0  0   1        0      0  
4        1        0  0  0  0  0   1        0      0  

[5 rows x 191 columns]

In [13]:
x['<1'].value_counts() #showing hidden data value prove's values exist in the dataframe

0    16535
1      722
Name: <1, dtype: int64

In [14]:
x['1000-4999'].value_counts()

0    16386
1      871
Name: 1000-4999, dtype: int64

In [15]:
x.dtypes

city_development_index    float64
training_hours            float64
city_1                      uint8
city_10                     uint8
city_100                    uint8
                           ...   
3                           uint8
4                           uint8
>4                          uint8
missing                     uint8
never                       uint8
Length: 191, dtype: object

In [16]:
x.isnull().sum()

city_development_index    0
training_hours            0
city_1                    0
city_10                   0
city_100                  0
                         ..
3                         0
4                         0
>4                        0
missing                   0
never                     0
Length: 191, dtype: int64

Importing train_test_split model for training and testing the model

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

Importing DecisionTreeClassifier

In [18]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()

In [19]:
tree.fit(x_train,y_train) #using fit() for training

DecisionTreeClassifier()

In [20]:
predictions=tree.predict(x_test) #using .predict() to predict the o/p of the model

In [21]:
predictions

array([1, 0, 1, ..., 1, 0, 1])

In [22]:
#importing confusion matrix & accuracy score for checking the accuracy of the model

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
acc=accuracy_score(y_test,predictions)

In [23]:
print(cm)

[[1358  372]
 [ 362 1360]]


In [24]:
print(acc) #accuracy using decision tree // additional comment to be notes that before one hot encoding the acc was around 74 but now it's been raised to 78%

0.787369640787949


Boosting the accuracy with Adaboost

In [25]:
from sklearn.ensemble import AdaBoostClassifier
ada_class=AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=20)

In [26]:
ada_class.fit(x_train,y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=20)

In [27]:
ada_prediction=ada_class.predict(x_test)

In [28]:
ada_prediction

array([1, 0, 1, ..., 1, 0, 1])

In [29]:
#importing confusion matrix & accuracy score again for checking the accuracy of the adaboost model

from sklearn.metrics import confusion_matrix,accuracy_score
CM=confusion_matrix(y_test,ada_prediction)
ACC=accuracy_score(y_test,ada_prediction)

In [30]:
print(CM)

[[1435  295]
 [ 310 1412]]


In [31]:
print(ACC)

0.824739281575898


Boosting the accuracy with Gradient Boosting

In [32]:
from sklearn.ensemble import GradientBoostingClassifier
grad_class=GradientBoostingClassifier(learning_rate=0.1)

In [33]:
grad_class.fit(x_train,y_train)

GradientBoostingClassifier()

In [34]:
grad_prediction=grad_class.predict(x_test)

In [35]:
grad_prediction

array([1, 0, 1, ..., 1, 0, 1])

In [36]:
#importing confusion matrix & accuracy score again for checking the accuracy of the GradientBoost model

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,grad_prediction)
acc=accuracy_score(y_test,grad_prediction)

In [37]:
print(cm)

[[1420  310]
 [ 260 1462]]


In [38]:
print(acc)

0.8348783314020858


Importing RandomForestClassifier

In [39]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [40]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [41]:
predictions=rf.predict(x_test)

In [42]:
predictions

array([1, 0, 1, ..., 1, 0, 1])

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
acc=accuracy_score(y_test,predictions)

In [44]:
print(cm)

[[1455  275]
 [ 287 1435]]


In [45]:
print(acc)

0.8371958285052143


Boosting the accuracy with Adaboost

In [46]:
from sklearn.ensemble import AdaBoostClassifier
ada_rf=AdaBoostClassifier(RandomForestClassifier(max_depth=1),n_estimators=20)

In [47]:
ada_rf.fit(x_train,y_train)

AdaBoostClassifier(estimator=RandomForestClassifier(max_depth=1),
                   n_estimators=20)

In [48]:
ada_predictions=ada_rf.predict(x_test)

In [49]:
ada_predictions

array([1, 0, 1, ..., 1, 0, 1])

In [50]:
#importing confusion matrix & accuracy score for checking the accuracy of the adaboost model

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,ada_predictions)
acc=accuracy_score(y_test,ada_predictions)

In [51]:
print(cm)

[[1402  328]
 [ 295 1427]]


In [52]:
print(acc) #here in randomforest when used adaboost it decreases the acc from 84% to 82%. So we'll try using gradientboost also

0.8195249130938587


Boosting the accuracy with Gradient Boosting

In [53]:
from sklearn.ensemble import GradientBoostingClassifier
grad_rf=GradientBoostingClassifier(learning_rate=0.1)

In [54]:
grad_rf.fit(x_train,y_train)

GradientBoostingClassifier()

In [55]:
grad_prediction=grad_rf.predict(x_test)

In [56]:
grad_prediction

array([1, 0, 1, ..., 1, 0, 1])

In [57]:
#importing confusion matrix & accuracy score for checking the accuracy of the gradientboost model

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,grad_prediction)
acc=accuracy_score(y_test,grad_prediction)

In [58]:
print(cm)

[[1419  311]
 [ 259 1463]]


In [59]:
print(acc) #here after using Gradient Boosting the accuracy got increase very slightly. Which became same as the decision tree classifier's gradient boosting

0.8348783314020858
